### PR TITLE
look for an `<audio>` tag

### PR DESCRIPTION
**Pull request by alxndr**
...and also the meta `og:title` tag. This will make it work on Bandcamp.

### CODE REVIEW

**Comment by ucpete** [comment]
I tried a few tracks on BandCamp and all failed. Do you have an URL that works, or is there some requirement I'm not satisfying about the type of track that can be yanked?

**Comment by alxndr** [comment]
Ah, cause I'm dumb

**Comment by ucpete** [comment]
Will test this and the others shortly – wrote a README over the course of the day.

**Comment by ucpete** [comment]
Bandcamp works, with title – nice!

Looks like this doesn't have the `[pre]` tag for SoundCloud, but the next PR (https://github.com/ucpete/mp3extractor/pull/3) has some SoundCloud fixes so I'm guessing that it's there. I'll accept this and we can sort through the merge on https://github.com/ucpete/mp3extractor/pull/3 separately. Haven't checked what the so-called 'conflicts' are yet but I imagine the merge should be trivial.

**Pull request merged**
